uploads = []

[[generated]]
id = "L_-Ti2eBGQAKntTJTX6SW"
uri = "file://artifacts/scam-alert/assets/images/icon.png"
type = "image"
title = "scam alert app icon"

[[generated]]
id = "LiIO7d47U36Pgw-DqvYEB"
uri = "file://artifacts/scam-alert/assets/images/splash-icon.png"
type = "image"
title = "scam alert splash"

[[generated]]
id = "6E7sSNqDJmxSMkC3bMQLS"
uri = "file://artifacts/scam-alert/assets/images/post-placeholder.png"
type = "image"
title = "scam alert post placeholder"

[[outputs]]
id = "a3UtBJ7V3Q_FUlH0AeAmV"
uri = "file://scam-alert-app.tar.gz"
type = "unspecified"
title = "Scam Alert — Full App Code"
