const shared = {
  primary:              "#FF3B3B",
  primaryForeground:    "#FFFFFF",
  primaryDark:          "#CC0000",
  primaryLight:         "#FF6B6B",
  destructive:          "#FF3B3B",
  destructiveForeground:"#FFFFFF",
  success:              "#22C55E",
  warning:              "#F59E0B",
  info:                 "#3B82F6",
  radius:               12,
};

const colors = {
  dark: {
    ...shared,
    background:          "#000000",
    surface:             "#0D0D0D",
    card:                "#1A1A1A",
    cardElevated:        "#252525",
    text:                "#FFFFFF",
    textSecondary:       "#9CA3AF",
    textMuted:           "#6B7280",
    secondary:           "#252525",
    secondaryForeground: "#FFFFFF",
    muted:               "#1A1A1A",
    mutedForeground:     "#9CA3AF",
    accent:              "#1A1A1A",
    accentForeground:    "#FF3B3B",
    border:              "#2D2D2D",
    input:               "#2D2D2D",
    tint:                "#FF3B3B",
    foreground:          "#FFFFFF",
  },

  light: {
    ...shared,
    background:          "#F9FAFB",
    surface:             "#FFFFFF",
    card:                "#FFFFFF",
    cardElevated:        "#F3F4F6",
    text:                "#0D0D0D",
    textSecondary:       "#374151",
    textMuted:           "#6B7280",
    secondary:           "#F3F4F6",
    secondaryForeground: "#0D0D0D",
    muted:               "#F3F4F6",
    mutedForeground:     "#6B7280",
    accent:              "#FEE2E2",
    accentForeground:    "#FF3B3B",
    border:              "#E5E7EB",
    input:               "#E5E7EB",
    tint:                "#FF3B3B",
    foreground:          "#0D0D0D",
  },

  "alert-red": {
    ...shared,
    primary:             "#FF1A1A",
    background:          "#0A0000",
    surface:             "#120000",
    card:                "#1E0000",
    cardElevated:        "#2A0505",
    text:                "#FFE5E5",
    textSecondary:       "#CC8888",
    textMuted:           "#994444",
    secondary:           "#2A0505",
    secondaryForeground: "#FFE5E5",
    muted:               "#1E0000",
    mutedForeground:     "#CC8888",
    accent:              "#3D0000",
    accentForeground:    "#FF1A1A",
    border:              "#3D1010",
    input:               "#3D1010",
    tint:                "#FF1A1A",
    foreground:          "#FFE5E5",
  },

  midnight: {
    ...shared,
    primary:             "#818CF8",
    background:          "#020617",
    surface:             "#0F172A",
    card:                "#1E293B",
    cardElevated:        "#334155",
    text:                "#F1F5F9",
    textSecondary:       "#94A3B8",
    textMuted:           "#64748B",
    secondary:           "#1E293B",
    secondaryForeground: "#F1F5F9",
    muted:               "#1E293B",
    mutedForeground:     "#94A3B8",
    accent:              "#334155",
    accentForeground:    "#818CF8",
    border:              "#334155",
    input:               "#334155",
    tint:                "#818CF8",
    foreground:          "#F1F5F9",
  },

  "safe-green": {
    ...shared,
    primary:             "#10B981",
    background:          "#001A0F",
    surface:             "#00261A",
    card:                "#003322",
    cardElevated:        "#00452F",
    text:                "#ECFDF5",
    textSecondary:       "#6EE7B7",
    textMuted:           "#34D399",
    secondary:           "#003322",
    secondaryForeground: "#ECFDF5",
    muted:               "#003322",
    mutedForeground:     "#6EE7B7",
    accent:              "#004D30",
    accentForeground:    "#10B981",
    border:              "#006644",
    input:               "#006644",
    tint:                "#10B981",
    foreground:          "#ECFDF5",
  },

  ocean: {
    ...shared,
    primary:             "#0EA5E9",
    background:          "#001824",
    surface:             "#002233",
    card:                "#003044",
    cardElevated:        "#004055",
    text:                "#E0F2FE",
    textSecondary:       "#7DD3FC",
    textMuted:           "#38BDF8",
    secondary:           "#003044",
    secondaryForeground: "#E0F2FE",
    muted:               "#003044",
    mutedForeground:     "#7DD3FC",
    accent:              "#004D6B",
    accentForeground:    "#0EA5E9",
    border:              "#0369A1",
    input:               "#0369A1",
    tint:                "#0EA5E9",
    foreground:          "#E0F2FE",
  },

  "purple-haze": {
    ...shared,
    primary:             "#A855F7",
    background:          "#0D0018",
    surface:             "#130022",
    card:                "#1E0033",
    cardElevated:        "#2D0047",
    text:                "#FAF5FF",
    textSecondary:       "#D8B4FE",
    textMuted:           "#A78BFA",
    secondary:           "#1E0033",
    secondaryForeground: "#FAF5FF",
    muted:               "#1E0033",
    mutedForeground:     "#D8B4FE",
    accent:              "#3B0066",
    accentForeground:    "#A855F7",
    border:              "#4C1D95",
    input:               "#4C1D95",
    tint:                "#A855F7",
    foreground:          "#FAF5FF",
  },
};

export default colors;
